name: Manual Go Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: '请输入版本号 (如 v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  fetch-branches:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.get-branches.outputs.branches }}
    steps:
    - name: Checkout all branches
      run: |
        git fetch --all
        echo "branches=$(git branch -r | grep -v HEAD | sed 's/origin\///' | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Get branches list
      id: get-branches
      run: echo "branches=${{ env.branches }}" 
      env:
        branches: ${{ env.branches }}
      continue-on-error: false
      
  build:
    runs-on: ubuntu-latest
    needs: fetch-branches
    strategy:
      matrix:
        branch: ${{ fromJSON(needs.fetch-branches.outputs.branches) }}
        os: [linux, windows, darwin]
        arch: [amd64, arm64]

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        ref: ${{ matrix.branch }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'

    - name: Build Go binaries
      run: |
        BRANCH=${{ matrix.branch }}
        OUTPUT_NAME=myapp-${{ matrix.os }}-${{ matrix.arch }}-${BRANCH}${{ matrix.os == 'windows' && '.exe' || '' }}
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o $OUTPUT_NAME .
        mkdir -p ./release-artifacts/${{ matrix.os }}
        mv $OUTPUT_NAME ./release-artifacts/${{ matrix.os }}/

    - name: Archive binaries by OS
      run: |
        cd ./release-artifacts/${{ matrix.os }}
        tar -czf ../myapp-${{ matrix.os }}-${{ matrix.arch }}-${BRANCH}-${{ inputs.version }}.tar.gz *
        cd ../..
    
    - name: Upload release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-${{ matrix.branch }}-${{ inputs.version }}
        path: ./release-artifacts/*.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./release-artifacts

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./release-artifacts/*.tar.gz
        tag_name: ${{ inputs.version }}
        release_name: Release ${{ inputs.version }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
