name: Manual Go Build and Release

on:
  workflow_dispatch:  # 手动触发
    inputs:
      version:
        description: '请输入版本号 (如 v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows]
        arch: [amd64, arm64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        # 获取所有分支
        fetch-depth: 0

    - name: Get all branches
      run: echo "BRANCHES=$(git branch -r | grep -v '\->' | sed 's/origin\///' | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Loop through branches and build
      run: |
        mkdir -p ./release-artifacts
        for OS in linux windows; do
          for ARCH in amd64 arm64; do
            mkdir -p ./release-artifacts/${OS}-${ARCH}
          done
        done

        for BRANCH in $BRANCHES; do
          echo "Building branch: $BRANCH"
          git checkout $BRANCH
          
          for OS in linux windows; do
            for ARCH in amd64 arm64; do
              echo "Building for OS: $OS, ARCH: $ARCH"
              FILENAME=SockFinder-${BRANCH}-${OS}-${ARCH}
              [[ $OS == "windows" ]] && FILENAME="${FILENAME}.exe"
              
              GOOS=$OS GOARCH=$ARCH go build -o $FILENAME .
              
              # 移动构建的文件到对应目录
              mv $FILENAME ./release-artifacts/${OS}-${ARCH}/
            done
          done
        done

    - name: Archive binaries by OS and ARCH
      run: |
        for OS in linux windows; do
          for ARCH in amd64 arm64; do
            tar -czf ./release-artifacts/SockFinder-${OS}-${ARCH}.tar.gz -C ./release-artifacts/${OS}-${ARCH} .
          done
        done

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./release-artifacts/SockFinder-*.tar.gz  # 只上传打包好的文件
        tag_name: ${{ inputs.version }}  # 使用输入的版本号作为标签
        release_name: ${{ inputs.version }}  # 使用输入的版本号作为发布名称
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
