name: Manual Go Build and Release

on:
  workflow_dispatch:  # 手动触发
    inputs:
      version:
        description: '请输入版本号 (如 v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows]
        arch: [amd64, arm64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}  # 使用触发时的分支

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'

    - name: Ensure release directory exists
      run: mkdir -p ./release-artifacts

    - name: Build Go binaries
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o myapp-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }} .


    - name: Archive binaries
      run: |
        tar -czf srusocks5update-${{ matrix.os }}-${{ matrix.arch }}.tar.gz myapp-${{ matrix.os }}-${{ matrix.arch }}
        mv myapp-${{ matrix.os }}-${{ matrix.arch }}.tar.gz ./release-artifacts/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./release-artifacts/myapp-*.tar.gz
        tag_name: ${{ inputs.version }}  # 使用输入的版本号作为标签
        release_name: ${{ inputs.version }}  # 使用输入的版本号作为发布名称
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
