name: Manual Go Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: '请输入版本号 (如 v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, darwin]  # 额外支持macOS
        arch: [amd64, arm64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}  # 使用触发时的分支

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'

    - name: Ensure release directory exists
      run: mkdir -p ./release-artifacts/${{ matrix.os }}

    - name: Build Go binaries
      run: |
        BRANCH=${{ github.ref_name }}
        OUTPUT_NAME=myapp-${{ matrix.os }}-${{ matrix.arch }}-${BRANCH}${{ matrix.os == 'windows' && '.exe' || '' }}
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o $OUTPUT_NAME .
        mv $OUTPUT_NAME ./release-artifacts/${{ matrix.os }}/

    - name: Archive binaries by OS
      run: |
        cd ./release-artifacts/${{ matrix.os }}
        tar -czf ../myapp-${{ matrix.os }}-${{ inputs.version }}.tar.gz *
        cd ../..
    
    - name: Upload release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-${{ matrix.os }}-${{ inputs.version }}
        path: ./release-artifacts/myapp-${{ matrix.os }}-${{ inputs.version }}.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./release-artifacts

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./release-artifacts/myapp-*.tar.gz
        tag_name: ${{ inputs.version }}
        release_name: Release ${{ inputs.version }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
