name: Manual Go Build and Release

on:
  workflow_dispatch:  # 手动触发
    inputs:
      version:
        description: '请输入版本号 (如 v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows]
        arch: [amd64, arm64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get all branches
      id: get-branches
      run: |
        BRANCHES=$(git ls-remote --heads origin | awk -F'/' '{print $NF}' | tr '\n' ' ')
        echo "BRANCHES=$BRANCHES" >> $GITHUB_ENV

    - name: Loop through branches and build
      shell: bash
      run: |
        ARTIFACTS_DIR=./release-artifacts-${{ github.run_id }}
        mkdir -p $ARTIFACTS_DIR

        for BRANCH in $BRANCHES; do
          echo "Building branch: $BRANCH"
          git checkout $BRANCH || { echo "Failed to checkout branch $BRANCH"; continue; }
          
          for OS in linux windows; do
            for ARCH in amd64 arm64; do
              echo "Building for OS: $OS, ARCH: $ARCH"
              SANITIZED_BRANCH=$(echo $BRANCH | sed 's/[^a-zA-Z0-9_-]/_/g')
              FILENAME=SockFinder-${SANITIZED_BRANCH}-${OS}-${ARCH}
              [[ $OS == "windows" ]] && FILENAME="${FILENAME}.exe"
              GOOS=$OS GOARCH=$ARCH go build -o $FILENAME . || { echo "Build failed for $OS/$ARCH"; continue; }
              DEST_DIR=$ARTIFACTS_DIR/${OS}-${ARCH}
              mkdir -p $DEST_DIR
              mv $FILENAME $DEST_DIR/
            done
          done
        done

    - name: Archive binaries by OS and ARCH
      shell: bash
      run: |
        ARTIFACTS_DIR=./release-artifacts-${{ github.run_id }}
        for OS in linux windows; do
          for ARCH in amd64 arm64; do
            DEST_DIR=$ARTIFACTS_DIR/${OS}-${ARCH}
            ARCHIVE_FILE=$ARTIFACTS_DIR/SockFinder-${OS}-${ARCH}.tar.gz
            if [ -d "$DEST_DIR" ] && [ "$(ls -A $DEST_DIR)" ]; then
              tar -czf $ARCHIVE_FILE -C $DEST_DIR .
              echo "Created archive: $ARCHIVE_FILE"
            else
              echo "No files to archive for $OS/$ARCH"
            fi
          done
        done

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./release-artifacts-${{ github.run_id }}/SockFinder-*.tar.gz
        tag_name: ${{ inputs.version }}
        name: ${{ inputs.version }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
