name: Go CI Build and Test

on:
  push:
    branches:
      - main
      - zjw345-patch-1-API-socks5
  pull_request:
    branches:
      - main
      - zjw345-patch-1-API-socks5
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: 'v1.0.0'  # 设置默认值
        type: string  # 参数类型为字符串

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows]
        arch: [amd64, arm64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Run tests
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go test ./...

    - name: Build Go binaries
      run: |
        echo "Building version: ${{ github.event.inputs.version }}"  # 打印输入的版本号
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o myapp-${{ matrix.os }}-${{ matrix.arch }}-${{ github.event.inputs.version }} .

    - name: Archive binaries
      run: |
        tar -czf myapp-${{ matrix.os }}-${{ matrix.arch }}-${{ github.event.inputs.version }}.tar.gz myapp-${{ matrix.os }}-${{ matrix.arch }}-${{ github.event.inputs.version }}
        mv myapp-${{ matrix.os }}-${{ matrix.arch }}-${{ github.event.inputs.version }}.tar.gz ./release-artifacts/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: myapp-binaries
        path: ./release-artifacts/myapp-*.tar.gz
